[2023-11-08T07:07:04.034+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:07:04.052+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:07:04.053+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-08T07:07:04.096+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:07:04.108+0000] {standard_task_runner.py:57} INFO - Started process 169 to run task
[2023-11-08T07:07:04.122+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmp7cnpzm72']
[2023-11-08T07:07:04.128+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask dbt_run
[2023-11-08T07:07:04.259+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e73511a18a1d
[2023-11-08T07:07:04.459+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T07:07:04.466+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T07:07:04.467+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models first_model --project-dir /home/marius.fall/NBA_Statistics/nba_stats && echo ok']
[2023-11-08T07:07:04.490+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T07:07:13.852+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2023-11-08T07:07:13.853+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2023-11-08T07:07:13.853+0000] {subprocess.py:93} INFO - 
[2023-11-08T07:07:13.854+0000] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/home/marius.fall/NBA_Statistics/nba_stats' does not exist.
[2023-11-08T07:07:14.273+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T07:07:14.305+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T07:07:14.312+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T070704, end_date=20231108T070714
[2023-11-08T07:07:14.346+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 169)
[2023-11-08T07:07:14.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T07:07:14.410+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-08T07:46:49.392+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:46:49.416+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T07:46:49.417+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-08T07:46:49.450+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T07:46:49.462+0000] {standard_task_runner.py:57} INFO - Started process 325 to run task
[2023-11-08T07:46:49.490+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpebr3c9_7']
[2023-11-08T07:46:49.496+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask dbt_run
[2023-11-08T07:46:49.662+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host e365784c7cfe
[2023-11-08T07:46:49.960+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T07:46:49.977+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T07:46:49.980+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /app/airflow/dbt_nba']
[2023-11-08T07:46:50.017+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T07:46:55.730+0000] {subprocess.py:93} INFO - [0m07:46:55  Running with dbt=1.7.0
[2023-11-08T07:46:55.737+0000] {subprocess.py:93} INFO - [0m07:46:55  Encountered an error:
[2023-11-08T07:46:55.738+0000] {subprocess.py:93} INFO - Runtime Error
[2023-11-08T07:46:55.738+0000] {subprocess.py:93} INFO -   Could not find profile named 'nba_stats'
[2023-11-08T07:46:56.447+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-08T07:46:56.482+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-08T07:46:56.490+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T074649, end_date=20231108T074656
[2023-11-08T07:46:56.520+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 325)
[2023-11-08T07:46:56.552+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T07:46:56.596+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-08T08:11:53.271+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T08:11:53.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-08T08:11:53.289+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-08T08:11:53.316+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 00:00:00+00:00
[2023-11-08T08:11:53.327+0000] {standard_task_runner.py:57} INFO - Started process 182 to run task
[2023-11-08T08:11:53.340+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpxgv74f9a']
[2023-11-08T08:11:53.347+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask dbt_run
[2023-11-08T08:11:53.551+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run scheduled__2023-11-07T00:00:00+00:00 [running]> on host 7a2338e7a8c3
[2023-11-08T08:11:53.749+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-08T08:11:53.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T08:11:53.780+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /app/airflow/dbt_nba']
[2023-11-08T08:11:53.809+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T08:12:01.336+0000] {subprocess.py:93} INFO - [0m08:12:01  Running with dbt=1.7.0
[2023-11-08T08:12:03.869+0000] {subprocess.py:93} INFO - [0m08:12:03  Registered adapter: bigquery=1.7.0
[2023-11-08T08:12:03.905+0000] {subprocess.py:93} INFO - [0m08:12:03  Unable to do partial parsing because profile has changed
[2023-11-08T08:12:05.815+0000] {subprocess.py:93} INFO - [0m08:12:05  [[33mWARNING[0m]: Did not find matching node for patch with name 'my_first_dbt_model' in the 'models' section of file 'models/example/schema.yml'
[2023-11-08T08:12:06.093+0000] {subprocess.py:93} INFO - [0m08:12:06  [[33mWARNING[0m]: Test 'test.nba_stats.unique_my_first_dbt_model_id.16e066b321' (models/example/schema.yml) depends on a node named 'my_first_dbt_model' in package '' which was not found
[2023-11-08T08:12:06.094+0000] {subprocess.py:93} INFO - [0m08:12:06  [[33mWARNING[0m]: Test 'test.nba_stats.not_null_my_first_dbt_model_id.5fb22c2710' (models/example/schema.yml) depends on a node named 'my_first_dbt_model' in package '' which was not found
[2023-11-08T08:12:06.180+0000] {subprocess.py:93} INFO - [0m08:12:06  Found 2 models, 2 tests, 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
[2023-11-08T08:12:06.188+0000] {subprocess.py:93} INFO - [0m08:12:06
[2023-11-08T08:12:06.944+0000] {subprocess.py:93} INFO - [0m08:12:06  Concurrency: 3 threads (target='dev')
[2023-11-08T08:12:06.945+0000] {subprocess.py:93} INFO - [0m08:12:06
[2023-11-08T08:12:06.953+0000] {subprocess.py:93} INFO - [0m08:12:06  1 of 2 START sql table model dbt_nba.first_model ............................... [RUN]
[2023-11-08T08:12:09.242+0000] {subprocess.py:93} INFO - [0m08:12:09  1 of 2 OK created sql table model dbt_nba.first_model .......................... [[32mCREATE TABLE (172.0 rows, 66.9 KiB processed)[0m in 2.29s]
[2023-11-08T08:12:09.246+0000] {subprocess.py:93} INFO - [0m08:12:09  2 of 2 START sql view model dbt_nba.my_second_dbt_model ........................ [RUN]
[2023-11-08T08:12:10.248+0000] {subprocess.py:93} INFO - [0m08:12:10  2 of 2 OK created sql view model dbt_nba.my_second_dbt_model ................... [[32mCREATE VIEW (0 processed)[0m in 1.00s]
[2023-11-08T08:12:10.260+0000] {subprocess.py:93} INFO - [0m08:12:10
[2023-11-08T08:12:10.261+0000] {subprocess.py:93} INFO - [0m08:12:10  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 4.07 seconds (4.07s).
[2023-11-08T08:12:10.277+0000] {subprocess.py:93} INFO - [0m08:12:10
[2023-11-08T08:12:10.278+0000] {subprocess.py:93} INFO - [0m08:12:10  [32mCompleted successfully[0m
[2023-11-08T08:12:10.280+0000] {subprocess.py:93} INFO - [0m08:12:10
[2023-11-08T08:12:10.282+0000] {subprocess.py:93} INFO - [0m08:12:10  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2023-11-08T08:12:11.370+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-08T08:12:11.472+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=extract, task_id=dbt_run, execution_date=20231107T000000, start_date=20231108T081153, end_date=20231108T081211
[2023-11-08T08:12:11.586+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T08:12:11.623+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
