[2023-11-07T17:51:37.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:51:37.977+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:51:37.978+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-07T17:51:37.995+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 17:32:08.537403+00:00
[2023-11-07T17:51:38.005+0000] {standard_task_runner.py:57} INFO - Started process 456 to run task
[2023-11-07T17:51:38.012+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'manual__2023-11-07T17:32:08.537403+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmp0nzr3xwp']
[2023-11-07T17:51:38.018+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask dbt_run
[2023-11-07T17:51:38.161+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [running]> on host 48017e158481
[2023-11-07T17:51:38.302+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T17:32:08.537403+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T17:32:08.537403+00:00'
[2023-11-07T17:51:38.313+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T17:51:38.314+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models first_model --project-dir /app/airflow/nba_stats/dbt_project.yml && echo ok']
[2023-11-07T17:51:38.337+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T17:51:42.234+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2023-11-07T17:51:42.235+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2023-11-07T17:51:42.235+0000] {subprocess.py:93} INFO - 
[2023-11-07T17:51:42.236+0000] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/app/airflow/nba_stats/dbt_project.yml' does not exist.
[2023-11-07T17:51:42.539+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-07T17:51:42.575+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-07T17:51:42.583+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T173208, start_date=20231107T175137, end_date=20231107T175142
[2023-11-07T17:51:42.602+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 456)
[2023-11-07T17:51:42.622+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T17:51:42.673+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
