[2023-11-07T17:47:07.008+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:47:07.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [queued]>
[2023-11-07T17:47:07.021+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-07T17:47:07.037+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-07 17:32:08.537403+00:00
[2023-11-07T17:47:07.047+0000] {standard_task_runner.py:57} INFO - Started process 350 to run task
[2023-11-07T17:47:07.054+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract', 'dbt_run', 'manual__2023-11-07T17:32:08.537403+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmpwks1zal0']
[2023-11-07T17:47:07.059+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask dbt_run
[2023-11-07T17:47:07.169+0000] {task_command.py:416} INFO - Running <TaskInstance: extract.dbt_run manual__2023-11-07T17:32:08.537403+00:00 [running]> on host 48017e158481
[2023-11-07T17:47:07.330+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T17:32:08.537403+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T17:32:08.537403+00:00'
[2023-11-07T17:47:07.335+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-07T17:47:07.335+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models first_model --project-dir /app/airflow/nba_stats/dbt_project.yml']
[2023-11-07T17:47:07.355+0000] {subprocess.py:86} INFO - Output:
[2023-11-07T17:47:12.323+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2023-11-07T17:47:12.324+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2023-11-07T17:47:12.325+0000] {subprocess.py:93} INFO - 
[2023-11-07T17:47:12.326+0000] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/app/airflow/nba_stats/dbt_project.yml' does not exist.
[2023-11-07T17:47:12.635+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-07T17:47:12.657+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-07T17:47:12.663+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=extract, task_id=dbt_run, execution_date=20231107T173208, start_date=20231107T174707, end_date=20231107T174712
[2023-11-07T17:47:12.682+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 350)
[2023-11-07T17:47:12.719+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T17:47:12.745+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
